Reverse strafe mouvement
WalkingMachine/wm_mecanum_cmd pull request #4
Opened 2017-03-24 17:18 UTC by maximest-pierre

Reverse the strafe mouvement so that the axis are not inverse

2017-03-26 01:59 UTC, gortium requested changes

2017-03-26 01:59 UTC, gortium commented on src/wm_mecanum_teleop_node.py
> +        twist.linear.y = self.maxLinearVelocity * vLinear * sin(Heading) * -1
Sure about that? It worked well before. If there is somewhere to change it is probably in the teleop.

2017-03-26 01:59 UTC, gortium commented on src/wm_mecanum_teleop_node.py
> +        twist.linear.y = self.maxLinearVelocity * vLinear * sin(Heading) * -1
Or the drives are not connected in the right order

2017-03-27 18:13 UTC, maximest-pierre commented on src/wm_mecanum_teleop_node.py
> +        twist.linear.y = self.maxLinearVelocity * vLinear * sin(Heading) * -1
They were always like that since I can remember. They were inverse during the Desjardins Shoot and also when we reconnect everything.

2018-05-17 01:47 UTC, closed without merging